hilichurlian_database/urls.py
from django.urls import path

from . import views

app_name = 'hilichurlian_database'
# be careful to not overlap with _project/urls.py
urlpatterns = [
	path('', views.index, name='index'),
	path('view', views.index, name='view'),
	path('about', views.about, name='about'),
	path('select', views.view_all_criteria, name='select'),
	path('filter', views.filter, name='filter'),
	path('utterance/<int:id>', views.view_utterance, name='utterance'),
	path('word/<slug:word>', views.view_word, name='word'),
	path('source/<int:id>', views.view_source, name='source'),
	path('speaker/<int:id>', views.view_speaker, name='speaker')
]

if views.SUBMISSIONS_OPEN:
	urlpatterns.append(path('submit', views.data_entry, name='data_entry'))
	# for POST
	urlpatterns.append(path('add_data/<slug:submit_type>', views.add_data, name='add_data'))

hilichurlian_database_project/urls.py
from django.contrib import admin
from django.urls import include, path
import os
from dotenv import load_dotenv

load_dotenv()
ADMIN_LOCATION = os.environ.get('DJANGO_ADMIN_LOCATION', 'admin/')

urlpatterns = [
	path(ADMIN_LOCATION, admin.site.urls),
	path('', include('hilichurlian_database.urls')),
]

hilichurlian_database/views.py
from email import message
from django.db.models import Q
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib import messages
from django.forms import modelform_factory
from .models import Speaker, Source, Word, CompleteUtterance
from .templatetags import describe_url
import re

import os
from dotenv import load_dotenv


### FORM CLASSES ###
CompleteUtteranceForm = modelform_factory(CompleteUtterance, fields=CompleteUtterance.FORM_FIELDS)
SourceForm = modelform_factory(Source, fields=Source.FORM_FIELDS)
SpeakerForm = modelform_factory(Speaker, fields=Speaker.FORM_FIELDS)

### GLOBAL CONSTANTS ###
DEFAULT_PAGE_SIZE = 10

load_dotenv()
SUBMISSIONS_OPEN = (os.environ.get('SUBMISSIONS_OPEN', 'False') == 'True')

### HELPER FUNCTIONS ###

def get_model_class(model_name):
	MODEL_MAPPING = {
		"Speaker": Speaker,
		"Source": Source,
		"Word": Word,
		"CompleteUtterance": CompleteUtterance,
		"Utterance": CompleteUtterance
	}
	return MODEL_MAPPING.get(model_name.capitalize())

def get_forms():
	return [
		{ "form_object": CompleteUtteranceForm(), "name": "utterance", },
		{ "form_object": SourceForm(), "name": "source", },
		{ "form_object": SpeakerForm(), "name": "speaker", }
	]

def remove_duplicates(may_have_duplicates):
	# keep order
	return list(dict.fromkeys(may_have_duplicates))

def generate_message(request, message_type, relevant_values):
	level_tag = messages.INFO
	extra_tags = ""
	message_text = ""
	values_html = ""
	for variable, value in relevant_values.items():
		values_html = values_html + variable + " - " + str(value) + "; "
	if values_html:
		values_html = values_html[:-2]

	if message_type == "successful new search":
		level_tag = messages.SUCCESS
		extra_tags = "searched"
		message_text = "Successfully found utterances that satisfy all of the following criteria: " + values_html
	elif message_type == "showing existing results":
		level_tag = messages.INFO
		extra_tags = "searched"
		message_text = "Showing utterances that satisfy all of the following criteria: " + values_html
	elif message_type == "invalid criteria found":
		level_tag = messages.ERROR
		extra_tags = "searched"
		message_text = "The following are not in the database: " + values_html
	elif message_type == "no results":
		level_tag = messages.ERROR
		extra_tags = "searched"
		message_text = "No utterances found that satisfy all of the following criteria: " + values_html
	elif message_type == "no valid criteria": # either empty or all invalid
		level_tag = messages.ERROR
		extra_tags = "searched"
		message_text = "Nothing found. Please enter a word, speaker, or source to search."
	messages.add_message(request, level_tag, message_text, extra_tags=extra_tags)
	return

# return the context object for the pages when browsing the database
def database_public_view_context(paginator, page_num, page_size, words="", similar = "", speaker="", source="", message_types={}):
	existing_criteria = "pageSize=" + str(page_size)
	if words:
		existing_criteria = existing_criteria + "&words=" + words
	if similar:
		existing_criteria = existing_criteria + "&similar=" + similar
	if speaker:
		existing_criteria = existing_criteria + "&speaker=" + speaker
	if source:
		existing_criteria = existing_criteria + "&source=" + source
	return {
		'db_page': paginator.get_page(page_num),
		'page_range': paginator.get_elided_page_range(page_num, on_each_side=2, on_ends=3),
		'page_range2': paginator.get_elided_page_range(page_num, on_each_side=2, on_ends=3),
		'page_size': page_size,
		'criteria': {
			'words': words,
			'similar': similar,
			'speaker': speaker,
			'source': source,
		},
		'existing': existing_criteria,
		'message_types': message_types,
	}


### VIEWS FOR POST ###

# submit_type is the "name" in the form object in data_entry() (the /submit page)
def add_data(request, submit_type):
	if SUBMISSIONS_OPEN and (request.method == 'POST') and submit_type:
		data = request.POST
		new_entry = submit_type
		if submit_type == "utterance":
			new_entry = CompleteUtterance()
			for label, value in data.items():
				if label in new_entry.SPECIALLY_HANDLED: # find existing ForeignKeys
					(object_for_field, created) = get_model_class(label).objects.get_or_create(id=value)
					setattr(new_entry, label, object_for_field)
				elif label in new_entry.FORM_FIELDS: # valid fields only!
					setattr(new_entry, label, value)
			new_entry.save() # save now for Word ManyToMany
			# get list of words; luckily, simple because no punctuation within words (yet)
			utterance_words = re.findall(r'\w+', data['utterance'].lower())
			for utt_word in utterance_words:
				(word_in_db, created) = Word.objects.get_or_create(word=utt_word)
				new_entry.words.add(word_in_db)
			new_entry.save()
		elif submit_type == "source":
			(source_in_db, created) = Source.objects.get_or_create(
				url = data['url'],
				defaults = { # only use these if source is new
					'name': describe_url.describe_url(data['url']),
					'version': data['version']
				}
			)
			if created:
				new_entry = source_in_db
			else:
				messages.error(request, '"' + str(source_in_db) + '" already exists')
		elif submit_type == "speaker":
			(speaker_in_db, created) = Speaker.objects.get_or_create(
				name = data['name'],
				defaults = { # only use these if speaker is new
					'type': data['type']
				}
			)
			if created:
				new_entry = speaker_in_db
			else:
				messages.error(request, '"' + str(speaker_in_db) + '" already exists')
		else:
			messages.error(request, "No data received")
		if new_entry != submit_type:
			messages.success(request, 'Added "' + str(new_entry) + '"')
	else:
		messages.error(request, "No data received")
	return redirect("hilichurlian_database:data_entry")


### VIEWS FOR USERS ###

def index(request):
	req = request.GET
	# initialize parameters
	render_page = "hilichurlian_database/index.html"
	page = req.get('page', 1)
	page_size = req.get('pageSize', DEFAULT_PAGE_SIZE)
	if int(page_size) < 1:
		page_size = 1
	if int(page) > 1:
		# go away, big home page blurb
		render_page = "hilichurlian_database/results.html"
	paging = Paginator(CompleteUtterance.objects.order_by('source', 'id'), page_size)
	return render(
		request,
		render_page,
		database_public_view_context(paging, page, page_size)
	)

# general
def view_entry(request, entry_queryset, entry_type, order=[]):
	render_page = "hilichurlian_database/entry.html"

	context = {"type": entry_type}
	if entry_queryset.exists():
		context["entry"] = entry_queryset.get()
		context["entry_values"] = context["entry"].get_fields_as_dict(order)

	return render(request, render_page, context)

def view_utterance(request, id):
	return view_entry(request, CompleteUtterance.objects.filter(id=id), "utterance", ["utterance", "words", "speaker", "translation", "translation_source", "context", "source"])

def view_word(request, word):
	return view_entry(request, Word.objects.filter(pk=word), "word", ["word", "variants_same_word", "variants_grammatical"])

def view_source(request, id):
	return view_entry(request, Source.objects.filter(id=id), "source", ["name", "url", "version", "related_sources"])

def view_speaker(request, id):
	return view_entry(request, Speaker.objects.filter(id=id), "speaker", ["name", "type"])

# for searching
# TODO: make this less scary
def filter(request):
	req = request.GET
	# initialize general parameters
	page = req.get('page', 1)
	page_size = req.get('pageSize', DEFAULT_PAGE_SIZE)
	if int(page_size) < 1:
		page_size = 1
	# initialize parameters to be updated
	utterances = CompleteUtterance.objects.all() # results
	all_variants = {} # word variants
	not_words = [] # from user's search
	# initialize search parameters
	want_grammatical_variants = req.get('similar', "").strip()
	speaker = req.get('speaker', "").strip()
	source = req.get('source', "").strip()
	new_search = req.get('newSearch', "")
	words_as_string = req.get('words', "").strip()
	words_list = re.findall(r'\w+', words_as_string.lower()) # like in add_data()

	# TODO: if wordA's variants_same_word includes wordB and variants_grammatical includes wordC, then wordB's variants_grammatical should also include wordC, but that's not enforced in models.py and views.py
	# get words to be searched for
	words_list = remove_duplicates(words_list)
	original_words_list = list(words_list)
	for word_string in original_words_list:
		word_query = Word.objects.filter(word=word_string)
		if not word_query.exists():
			not_words.append(word_string)
			words_list.remove(word_string)
			continue
		word_object = word_query.get()
		all_variants[word_string] = word_object.variants_same_word.union(Word.objects.filter(word=word_string)) # Words are currently not variants of themselves
		if want_grammatical_variants and word_object.variants_grammatical.exists():
			all_variants[word_string] = all_variants[word_string].union(word_object.variants_grammatical.all())
	# regenerate words_as_string
	words_as_string = ""
	for w in words_list:
		words_as_string = words_as_string + w + " "
	words_as_string = words_as_string[:-1]
	
	# prepare invalid info about search
	nonexistent_values = {}
	if not_words:
		nonexistent_values["words"] = str(not_words)[1:-1]
	if speaker and not Speaker.objects.filter(name=speaker).exists():
		nonexistent_values["speaker"] = speaker
		speaker = ""
	if source and not Source.objects.filter(url=source).exists():
		nonexistent_values["source"] = source
		source = ""
	if nonexistent_values:
		generate_message(request, "invalid criteria found", nonexistent_values)

	# get utterances within search_set that match speaker and source
	if speaker:
		utterances = utterances.filter(speaker__name=speaker)
	if source:
		utterances = utterances.filter(source__url=source)
	# now that the set is smaller, get utterances that have all of the words
	# TODO: handle case where grammatical variations are specifically specified (e.g. user enters "mi mimi") so that anything the user enters is required
	for w in words_list:

hilichurlian_database/templates/hilichurlian_database/about.html
{% extends "hilichurlian_database/base.html" %}
{% load static %}

{% block content %}
<h2>About</h2>

<p>This website was created and is maintained by a <a href="https://genshin-impact.fandom.com/">Genshin Impact Fandom Wiki</a> editor.</p>

<p>I created this website half because I believe hiliologists need it and half because I wanted to learn something new (namely, how to deploy a website using Heroku).</p>

<p>To send feedback about this database website, please join <a href="https://discord.com/invite/CVKTBANp">the Genshin Impact Wiki's Discord server</a> and send a message in the <i>#genshin-languages</i> channel, which is viewable upon self-assigning the Lore role in the <i>#librarians-rules</i> channel. I promise I don't bite.</p>

<p>Unordered to-do list:</p>
<ul>
	<li>get an actual color scheme</li>
	<li>figure out page structure</li>
	<li>API or something, especially now that words are linked together as exact same variants and likely grammatical variants</li>
	<li>links on individual entry pages</li>
	<li>option to view cells in bigger boxes
		<ul>
			<li>option to view an individual cell in an overlay box or expand the cell or something (fallback: view entire row on its own page)</li>
		</ul>
	</li>
	<li>filter by speaker
		<ul>
			<li>may want to filter by type of speaker (e.g. native speaker vs student)
				<ul>
					<li>may want to search for Jacob Musk, Ella Musk, and Ella Musk's grandfather (possibly Jacob Musk but unconfirmed) at the same time (all/both are dedicated Hilichurlian scholars)</li>
				</ul>
			</li>
			<li>Hilichurls are distinguished from each other when possible, but we'll want to search for all Hilichurl utterances together</li>
			<li>maybe we should distinguish between Hilichurls? e.g. happy ones, unhappy ones; this might be better as a new field</li>
		</ul>
	</li>
	<li>filter by source
		<ul>
			<li>for series of books with multiple volumes, they should be searchable separately and together</li>
		</ul>
	</li>
	<li>add "Related words/sources" aside to results of exact search</li>
	<li>don't think these would be of much help, but may as well also filter by translation sources and words in translations</li>
	<li>add "Viewing results X to Y out of Z total results"</li>
	<li>user-friendly way of specifying page size
		<ul>
			<li>"show all" option (page size is same as number of utterances)</li>
			<li>buttons with sample/preset values</li>
		</ul>
	</li>
	<li>form validation (e.g. pageSize should be a positive integer)</li>
	<li>un-spaghetti the things that are starting to become spaghetti</li>
</ul>

<p>Done:</p>
<ul>
	<li>option to view an entire row on its own page</li>
	<li>new field "version" to show which utterances have been available since which versions of the game (Ella has apparently improved over time, but some of her old dialogue is not updated)</li>
	<li>display lists of all words, speakers, sources; let them link to queries</li>
	<li>text field to specify custom page size</li>
	<li>condensed pagination</li>
	<li>filter by Hilichurlian word
		<ul>
			<li>filter by exact word (e.g. to avoid picking up all instances of <i>mita</i> when looking for just <i>mi</i>)</li>
			<li>filter not by exact word (e.g. to pick up all instances of <i>mimi</i> when looking for <i>mi</i> if so desired); implemented as variants of the same word (e.g. "nya" is the same as "nyaaaa") and likely grammatical variants (e.g. "da" and "dada")</li>
			<li>filter by multiple words (e.g. all utterances with both <i>mosi</i> and <i>mita</i>; any separator other than letters)</li>
		</ul>
	</li>
	<li>filter by source (currently exact URLs only)</li>
	<li>filter by speaker (currently exact speaker only)</li>
</ul>

{% endblock %}

hilichurlian_database/templates/hilichurlian_database/base.html
{% load static %}
<!doctype html>
<html lang="en-US">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Hilichurlian Language Database</title>
	<link rel="shortcut icon" href="{% static 'hilichurlian_database/favicon.ico' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'hilichurlian_database/style.css' %}">
</head>
<body>
	<header>
		<a href="#main" id="skip-to-main" class="skip-to">Skip to main content</a>
		
		<h1>Hilichurlian Language Database</h1>

		<nav>
			<a href="{% url 'hilichurlian_database:index' %}">Home</a>
			<a href="{% url 'hilichurlian_database:about' %}">About</a>
			<a href="{% url 'hilichurlian_database:select' %}">View All Criteria</a>
		</nav>
	</header>

	<main id="main">
		{% if messages %}{% if message_types.non_search_messages %}
		<section>
			<h2>Information</h2>
			<ul class="messages">
				{% for message in messages %}{% if "searched" not in message.tags %}
				<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
				{% endif %}{% endfor %}
			</ul>
		</section>
		{% endif %}{% endif %}

		<article>
			{% block content %}
			{% endblock %}
		</article>
	</main>

	<footer>
		<img id="img-three-hilichurls" src="{% static 'hilichurlian_database/hilichurls.png' %}" alt="Three Hilichurls: one sleeping, one chilling, and one sweating while holding a Pyro Slime." class="bordered-image" />
		<div class="text">
			<p>This site is not affiliated with or endorsed by miHoYo.</p>
			<p>© All rights reserved by miHoYo. Other properties belong to their respective owners.</p>
			<div id="donate-container" class="container flex">
				<div>
					<p>Want to help me cover website costs?</p>
					<a href="https://ko-fi.com/solarmist">Donate to me on Ko-fi. <img id="img-ko-fi-cup" src="https://storage.ko-fi.com/cdn/brandasset/kofi_s_logo_nolabel.png" alt="Ko-fi cup" /></a>
				</div>
				<div>
					<img id="img-lumine" src="https://static.wikia.nocookie.net/gensin-impact/images/e/ee/Icon_Emoji_016_Lumine_Will_1_Mora_do%3F.png/revision/latest?cb=20210906043859" alt="Lumine with a tear in one eye sheepishly holding 1 Mora."/>
				</div>
			</div>
		</div>
	</footer>
</body>
</html>

hilichurlian_database/templates/hilichurlian_database/entry.html
{% extends "hilichurlian_database/base.html" %}
{% load static %}

{% block content %}

{% if entry %}

	<h2>{{ type|capfirst }}: {{ entry }}</h2>

	<div class="container flex flex-center">
	{% for field, value in entry_values.items %}

	{% if field == 'translation' %}<div class="container flex wide invisible-container">{% endif %}{# keeping certain boxes together #}

		<section class="flex {% if field == 'context' and value %}medium{% else %}thin{% endif %}">
			<h3>{{ field|capfirst }}</h3>
			{% if value.0 %} {# all items currently wrapped in lists to differentiate from strings #}
				{% if value.1 %}{# value has multiple items #}
					<p>{% for item in value|slice:":-1" %}<a href="#">{{ item }}</a>, {% endfor %}<a href="#">{{ value|last }}</a></p>
				{% else %}
					<p>{% if value.0.word %}<a href="#">{% endif %}
						{{ value.0|linebreaks }}
					{% if value.0.word %}</a>{% endif %}</p>

					{% if field != "context" and field != "source" and "(" in value.0 %}<p>(Context)</p>{% endif %}

					{% if field != "context" and field != "source" and "[" in value.0 %}<p>(Edited from original indirect translation)</p>{% endif %}
				{% endif %}
			{% else %}
				<p>(None found)</p>
			{% endif %}
		</section>

	{% if field == 'translation source' %}</div>{% endif %}

	{% endfor %}
	</div>

{% else %}

	<h2>Entry Not Found</h2>

	<p>This was probably something that I made by accident while I was still building the database and later had to delete.</p>
	<p><a href="{% url 'hilichurlian_database:index' %}">Go back home</a></p>

{% endif %}

{% endblock %}

hilichurlian_database/templates/hilichurlian_database/index.html
{% extends "hilichurlian_database/base.html" %}
{% load static %}

{% block content %}

<div class="messages information">
	<p>Welcome to the Hilichurlian Language Database! This website is a repository for all utterances of the Hilichurlian language..</p>
	<p>The database only contains official or "official" translations (in English) of Hilichurlian. Some educated guesswork was performed when deciding which utterances had translations provided, but aside from that, there is nothing unofficial in this database.</p>
	<p>More features are on the way! Check the <a href="{% url 'hilichurlian_database:about' %}">About page</a> for more details.</p>
</div>

{% include "hilichurlian_database/elements/table.html" %}

{% endblock %}

hilichurlian_database/templates/hilichurlian_database/results.html
{% extends "hilichurlian_database/base.html" %}
{% load static %}

{% block content %}
{% include "hilichurlian_database/elements/table.html" %}
{% endblock %}

hilichurlian_database/templates/hilichurlian_database/select.html
{% extends "hilichurlian_database/base.html" %}
{% load static %}

{% block content %}
<h2>View All Criteria</h2>
<div class="messages information">
	<p>Click any of the links below to view the corresponding utterances.</p>
	<p>IMPORTANT: There is a good chance that this page will be renamed, because I honestly don't know what good names for this page are.</p>
</div>

<div class="container flex">
	<section class="flex medium">
		<h3>All Sources</h3>
		<ul>
			{% for source in sources %}
			<li><a href="{% url 'hilichurlian_database:filter' %}?source={{source.url}}">{{ source }}</a> (Version {{ source.version }})</li>
			{% endfor %}
		</ul>
	</section>

	<section class="flex medium">
		<h3>All Speakers</h3>
		<div class="container flex">
		{% for type in speaker_types %}
			<div class="flex thin inner">
				<h4>{% if type.1 != "Unknown" %}{{ type.1 }}{% else %}Other{% endif %}</h4>
				<ul>
					{% for speaker in speakers %}{% if speaker.type == type.0 %}
					<li><a href="{% url 'hilichurlian_database:filter' %}?speaker={{speaker}}">{{ speaker }}</a></li>
					{% endif %}{% endfor %}
				</ul>
			</div>
		{% endfor %}
		</div>
	</section>

	<section class="flex wide">
		<h3>All Words</h3>
		<ul>
			{% for word in words %}
			<li><a href="{% url 'hilichurlian_database:filter' %}?words={{word}}">{{ word }}</a></li>
			{% endfor %}
		</ul>
	</section>
</div>
{% endblock %}

hilichurlian_database/templates/hilichurlian_database/submit.html
{% extends "hilichurlian_database/base.html" %}
{% load static %}

{% block content %}
<h2>Submit Data</h2>

<div class="messages information">
	<p>Please note the following:</p>
	<ul>
		<li>All information, including translation information, must be taken directly from the game or other official material.
			<br /><strong>No guesses, no matter how good they are.</strong>
			<br />However, you may make educated guesses about which utterances correspond to provided translations as well as which provided translations are direct translations.</li>
		<li>All information must be from the English localization of Genshin Impact, but notable differences between the English localization and the original Chinese texts may be added as additional notes.</li>
		<li>An "<strong>utterance</strong>" is basically a sentence, including sentence fragments and otherwise not grammatical sentences. Utterances can technically be individual phrases and words if they make up "sentences" by themselves.</li>
		<li><strong>Translations</strong> that are given indirectly (e.g. "It said that its friend knows") may be rephrased to become direct translations with brackets around the words that were changed (e.g. "[My] friend knows").</li>
		<li><strong>Translation sources</strong> are people or written material such as books.</li>
	</ul>
	<p>Data may be cleaned some time after entry.</p>
	<p>This submission page is temporary and will be taken down once the database has been sufficiently updated.</p>
	<p>I'm hoping everyone who submits something does so in good faith!</p>
</div>

{% for form in forms %}
<form method="POST" action="{% url 'hilichurlian_database:add_data' form.name %}" id="{{ form.name }}-form" class="long-form">
	{% csrf_token %}
	<fieldset>
		<legend>New <strong>{{ form.name }}</strong></legend>
		{% for field in form.form_object %}
		<div class="form-field">
			<label class="field-label{% if field.field.required %} field-required{% endif %}" for="id_{{ field.name }}">{{ field.label }}</label>
			{{ field }}
		</div>
		{% endfor %}
		<input type="submit" value="Submit">
	</fieldset>
</form>
{% endfor %}

{% endblock %}